"""added column user_id for table category

Revision ID: 8b8dd705330b
Revises: 981f17e6cc32
Create Date: 2023-07-26 00:28:26.103567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b8dd705330b'
down_revision = '981f17e6cc32'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('user_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'category', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'category', type_='foreignkey')
    op.drop_column('category', 'user_id')
    # ### end Alembic commands ###
